### ISSUE TITLE
登录逻辑的修改

### ISSUE THREAD

**Issue by shiguangbiyi** [TongjiPetWelfareProject/DB_PetWelfare#15]
现在决定用电话作为登录的方法凭证，那数据库中应该以电话为超码了，数据库和后端文件应该有相应调整。
@VictorHuu @asceking

**Comment by VictorHuu** [comment]
验证码还是密码

**Comment by shiguangbiyi** [comment]
用户输入电话号码和密码即可登录

**Comment by shiguangbiyi** [comment]
这种网站用户记得自己的uid可能性比较小，考虑用户需求还是电话号码更方便而且也合理
