### ISSUE TITLE
个人页面点赞宠物数据

### ISSUE THREAD

**Issue by Aquilune** [TongjiPetWelfareProject/DB_PetWelfare#18]
![image](https://github.com/shiguangbiyi/DataBase_Program_Pet-Rescue-Station/assets/126951839/4fc7b601-2df1-49f9-8985-d78942b24271)
这个个人页面中“我的点赞”，通过发送user_id，返回该用户点赞的所有宠物的{{宠物id和宠物信息}}，用json形式打包，其中宠物id用于点击跳转到对应宠物详情页面的路由，宠物名称用于展示在该页面。
收藏同理。
评论亦同理，但要多返回一个{评论内容}供该页面展示.
浏览暂时不管吧，可能不合理要删。
接口：
/api/likepet
/api/collectpet
/api/commentpet
@asceking @VictorHuu

**Comment by shiguangbiyi** [comment]
该页面的业务逻辑很简单，就是基本的查询功能，整个页面都只有两个业务逻辑，所以不要耽误太多时间
